---

- hosts: all
  become: true

  tasks:
    - name: Crear la estructura de directorios
      file:
        path: "/tmp/2do_parcial/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - alumno
        - equipo

    - name: Crear archivo de datos del alumno
      copy:
        content: |
          Nombre: Mateo Apellido: Corbetto
          Division: 115
        dest: "/tmp/2do_parcial/alumno/datos_alumno.txt"
        mode: '0644'

    - name: Crear archivo de datos del equipo
      copy:
        content: |
          IP: "{{ ansible_default_ipv4.address }}"
          Distribucion: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          Cantidad de Cores: "{{ ansible_processor_cores }}"
        dest: "/tmp/2do_parcial/equipo/datos_equipo.txt"
        mode: '0644'

    - name: Configurar sudoers para permitir el uso de sudo sin contraseña para el grupo %2PSupervisores
      lineinfile:
        path: "/etc/sudoers.d/2PSupervisores"
        line: "%2PSupervisores ALL=(ALL) NOPASSWD:ALL"
        create: yes
        mode: '0440'

    - name: Otra tarea
      debug:
        msg: "Despues de la ejecucion del rol"
